FROM alpine

RUN apk update && apk add curl

RUN curl -o /etc/apk/keys/virtuozzo.rsa.pub http://kojistorage.eng.sw.ru/alpine/ploop/v7.0.88/virtuozzo.rsa.pub 
RUN echo http://kojistorage.eng.sw.ru/alpine/ploop/v7.0.88/ >> /etc/apk/repositories

RUN apk update && apk add go ploop gptfdisk ploop-dev pkgconfig gcc build-base musl-dev linux-headers

COPY . /go/src/github.com/virtuozzo/docker-volume-ploop
WORKDIR /go/src/github.com/virtuozzo/docker-volume-ploop
ENV GOPATH=/go

RUN go install

CMD ["/go/bin/docker-volume-ploop"]
